Feature one pull request
Tarto-4/Hello-world pull request #1
Opened 2023-04-25 08:57 UTC by Tarto-4

2023-04-25 09:40 UTC, Olamarx requested changes
Hi @Tarto-4, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>

## Highlights
- Linters passed ✔️

## Required Changes ♻️
_Check the comments under the review._
### I would have commented under the readme but it is merged and no changes in it.
- [x] I would advise you to fill in all the data required in the readme file, note that all the sections are required except the FAQ, kindly remove all the dummy data and fill them in according to your project.
- [x] I will implore you to always name your feature branch according to what you are doing in the branch such as  'created_sidebar' or 'added_comments_section', in this case, it can be 'microverse_hello_world' or anything related. To achieve this, kindly checkout to a new branch and use the correct name and mention this old PR in the new PR.
- [x] Kind always make your PR description and always make it descriptive. A descriptive PR has a heading and a list of what was done under it.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 10:40 UTC, Tarto-4 commented
Filled in required data for readme

2023-04-25 11:25 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @Tarto-4  👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 11:25 UTC, AbelG101 commented on README.md
- [ ] Kindly make sure to remove all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
Kindly remove this:
  - > Describe 1 - 3 features you will add to the project.
- [ ] Please make sure to only add the tech stack that you've used for the project. So please replace the default tech stacks listed in the tech stack section with what you've used like HTML5 & CSS3
- [ ] Please make sure to add key features to your project, it could be as simple as "displays Hello Microverse" 📌 as it gives a good overview to the reader of what to look at.
- [ ] I noticed the Live demo link redirects to Google 😅 but please make sure all the links on your readme work properly and redirect to the proper page. You can remove the live demo link section if you don't plan on deploying the project and it's not a project requirement. 
- [ ] Kindly make sure to add clear and detailed steps on how to get started with your project such as the prerequisites, setting up, etc... the default text should be removed 🎯
- [ ] Please make sure the "Future Features section" contains at least 1 feature you'll be adding in the near future this shows future clients you've got a growth mindset by continuously adding features to your project👍.
- [ ] The MIT link is currently broken so please make sure to fix it as it shows this project has an appropriate license. The reason it doesn't work is that you don't have an MIT.md file on your repo so please add that file (you can find it [here](https://github.com/microverseinc/readme-template/blob/master/MIT.md)) and modify the content inside that file with your personal info, and finally add that file as a link like this: `./MIT.md` to your MIT link.
- [ ] Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
Kindly remove this:
    -  _NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish._

2023-04-25 14:13 UTC, AbeeraTahir requested changes
# Status: Changes Required ♻️

Hi @Tarto-4, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ Great effort on implementing the changes suggested by the previous reviewers

 ## Required Changes ♻️
 - [ ] The [PR](https://github.com/Tarto-4/Hello-world/pull/2) that you mentioned here, I cannot see the linters green check, please fix this issue to meet the project requirements. 😊
 - [ ] Referring to your [this](https://github.com/Tarto-4/Hello-world/pull/2/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) README file from the [PR](https://github.com/Tarto-4/Hello-world/pull/2) that you mentioned here, kindly make sure to use [Microverse README template](https://github.com/microverseinc/readme-template.git), with all of the correct headers and table of contents, so that it will look more professional. 😊
 - [ ] Kindly make sure to add all relevant headers like `tech stack` `key features`, `future features`, etc. to your README file, and all mentioned in  [Microverse README template](https://github.com/microverseinc/readme-template.git) so that it will provide all of the necessary information about your project.
 - [ ] Please write the steps for setting up your project under the respective headings, as described in the [template](https://github.com/microverseinc/readme-template.git), to give a clear picture of setting up your project to the readers.
 - [ ] Please replace `repository URL` here `git clone {repository URL}`, with the URL of your repo, so that readers can have an idea of cloning your repo.
 - [x] Please make sure to write the correct project name here `open your directory math-magician/`, as your project is not the `math-magician` one. 😊

## Optional suggestions

- [ ] [OPTIONAL] Kindly make sure to write your commit messages in imperative tense and capitalized, to make them more meaningful and easier to understand.😄 For more information, please check [this](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) curriculum.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 09:21 UTC, bobb-Rob commented
@tarto-4, please check [this ](https://github.com/Tarto-4/Hello-world/pull/2#pullrequestreview-1401492940)pull request for my comments on the project.

2023-04-26 10:55 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Tarto-4, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 10:55 UTC, bobb-Rob commented on .github/workflows/linters.yml
> +    steps:
- [ ] This pull request has no summary/description and a proper title. Kindly use a more descriptive title and provide a detailed summary of the thing you did in the project. 

![image](https://user-images.githubusercontent.com/84156714/234553719-c389e6c4-ec84-49d2-9613-c3952a78914f.png)

E.g of a descriptive
- Title: Hello Microverse Project
- Summary: 👇🏾 
   ```
        Hello Microverse
        -  Add error checking linters.yml file
        -  Add a descriptive readme using markdown syntax
        -  Add HTML file
        -  Add CSS styling
```

2023-04-26 12:16 UTC, merged