Microverse hello world
Tarto-4/Hello-world pull request #2
Opened 2023-04-25 10:58 UTC by Tarto-4

### **New pull request**
@olamarx
This is a new pull request of the branch that has required contents that were missing on : https://github.com/Tarto-4/Hello-world/pull/1
Updated readme file 
Updated branch name

2023-04-25 18:06 UTC, skyv26 requested changes
## Hi @Tarto-4 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://camo.githubusercontent.com/281a5636431ea0a84905c663c68ae7b10274611bea0daf9cc0d7d2ab6a679584/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f375379476b4f306b515743666e55433437592f67697068792e676966)

 ## Required Changes ♻️
- [x] Please use only one `PR` for the next time. your previous pull request was #1 and make sure only use one pull request in each branch to request for review, using multiple branches and PRs to request for review is unprofessional. Kindly look at the [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 18:06 UTC, skyv26 commented on README.md
> -- [📝 License](#license)
- [x] Kindly use the [Microverse README.md Template](https://github.com/microverseinc/readme-template) as mentioned by the previous code reviewer in your [#1](https://github.com/Tarto-4/Hello-world/pull/1#pullrequestreview-1399898288) pull request. Somehow you did a great job in your work by implementing the changes asked by the previous code reviewer but you still made a mistake by deleting the important part of the project. 
- Please consider the `above-highlighted` table in your `README.md` file which can actually help any person to directly jump on to a `specific` feature or `information` of the project.

2023-04-25 18:06 UTC, skyv26 commented on README.md
> -<!-- Features -->
- [x] Please add the above-removed snippet back in your `README.md` file because it will make `README.md` file informative and tell any person easily about the name of the project and about the `tech stacks` that you used because sometimes a person can run into the problem who don't have the prior experience.

2023-04-25 18:06 UTC, skyv26 commented on README.md
> -
- [x] Please add the `key features` of your project which make the user aware of what kind of features are in your project. Kindly add at least *one* key feature.

2023-04-25 18:06 UTC, skyv26 commented on README.md
> - -->
- [x] Please consider the `above-highlighted` snippet in your `README.md` file and customised it in such a way that it helps any user about how to use the project and what are the `pre-requisite` before working on or using the project. Please look at the below-attached image.

![Screenshot from 2023-04-25 19-31-28](https://user-images.githubusercontent.com/66476329/234356134-7fb0c481-fde4-449f-8a04-5dd8d5d55e36.png)

2023-04-25 18:06 UTC, skyv26 commented on README.md
> ---->
- [x] Kindly add the `above-highlighted` section in your `README.md` file which will help the user how to set up the project and start working on it. I would suggest you always keep the `normal` user perspective while working on the project or `documentation`. Please look at the below image.

![Screenshot from 2023-04-25 19-30-56](https://user-images.githubusercontent.com/66476329/234356611-1e233a5c-3bc5-4820-8971-db4de7c52b30.png)

2023-04-25 18:06 UTC, skyv26 commented on README.md
> +$ git clone {repository URL}
- [x] Kindly replace `{repository URL}` with your repository link,  so that it will be convenient for any person to use your project without any conflicts.

2023-04-25 18:06 UTC, skyv26 commented on README.md
> +> open your directory math-magician/
- [  ] Please add the above-removed lines of instructions back to your `README.md` file as I also gave an example in my previous comment.

*Friendly Note*: Please remove the `> xyz text` line from your whole `README` file because it is just a placeholder to instruct the developer to create beautiful documentation.

2023-04-25 18:06 UTC, skyv26 commented on README.md
> -- [ ] **[new_feature_3]**
- `[OPTIONAL]` Please add at least one `future feature` which will create interest in the user who going to use your project.

2023-04-26 09:20 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @Tarto-4, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

 ## Required Changes ♻️

- [x] As the previous reviewer mentioned, linter checks are not running on this pull request. Please fix this and ensure they are running and all turn green. 
- [x] Please when requesting a review after fixing all issues raised here, please submit this pull request and not the previous one.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 09:20 UTC, bobb-Rob commented on README.md
> +# 📖 [Microverse Hello world] <a name="about-project"></a>
- [x] Usually, square brackets are used for placeholder text, but since you have replaced the placeholder text with the title of your project, you should remove the `[` and `]` from both titles on lines 57 and 59.

2023-04-26 09:20 UTC, bobb-Rob commented on README.md
> +- **[no key_2]**
- [x] As I said earlier, you should remove square brackets `[` and `]` on lines 92, 93, and 94. Also, please you should add actually meaningful features to this README. I know this project is too basic with almost no feature, but the goal of this project is to teach you how to document your project professionally. This skill will be useful in the next projects you will complete in Microverse. You could put anything like 👇🏾 

- **Html header text**
- **CSS background Color property used**
- **Markdown syntax used**

2023-04-26 09:20 UTC, bobb-Rob commented on README.md
>  👤 **Author1**
- [x] You should use your name here. this will help any user know that the handle below belongs to you.

2023-04-26 09:20 UTC, bobb-Rob commented on README.md
>    <summary>Client</summary>
- [ ] The tech stack that you used is HTML and CSS. Please remove the REACTJS, EXpress, and Postgress below. 

```html

<details>
  <summary>Client</summary>
  <ul>
    <li><a href="#">React.js</a></li> <!-- Replace this REACT with HTML -->
   <li><a href="#">CSS</a></li> <!-- Add a new line with CSS -->
  </ul>
</details>
<!-- Remove from here -->
<details>
  <summary>Server</summary>
  <ul>
    <li><a href="https://expressjs.com/">Express.js</a></li>
  </ul>
</details>
<details>
<summary>Database</summary>
  <ul>
    <li><a href="https://www.postgresql.org/">PostgreSQL</a></li>
  </ul>
</details>
```

2023-04-26 10:22 UTC, closed without merging